version: "3.9"

services:
  db:
    image: bitnami/mysql:8.0.27
    container_name: shape-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: shape
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - shape_db_volume:/bitnami/mysql/data
      - ../../init/db:/docker-entrypoint-initdb.d
    networks:
      - shape

  db-gui:
    image: phpmyadmin/phpmyadmin
    container_name: shape-db-gui
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: shape-db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - 8081:80
    restart: unless-stopped
    networks:
      - shape

networks:
  shape:
    driver: bridge

volumes:
  shape_db_volume: null
